.\"
.\" Copyright (c) 2016-2018  Joachim Nilsson <troglobit@gmail.com>
.\"
.\" Permission to use, copy, modify, and/or distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd Jan 3, 2018
.Dt WATCHDOGCTL 1
.Os "watchdogd (3.0)"
.Sh NAME
.Nm watchdogctl
.Nd Status and control tool for watchdogd
.Sh SYNOPSIS
.Nm
.Op Fl hvV
.Op clear
.Op disable | enable
.Op debug
.Op loglevel Ar LEVEL
.Op reload
.Op reset Op MSEC
.Op status
.Op test Op TEST
.Sh DESCRIPTION
.Nm
provides a safe way of querying status and controlling 
.Xr watchdogd 8 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl v, -verbose
Enable verbose mode, otherwise commands are silent.
.It Fl V, -version
Show version information.
.It Fl h, -help
Show help message.
.El
.Sh COMMANDS
Short forms of the below commands are allowed, as long as it is unique.
.Bl -tag -width Ds
.It Cm clear
Clear reset cause.
.It Cm counter
Show reset counter, number of reboots since power-on.
.It Cm debug
Toggle daemon debug log level.  See also the
.Cm loglevel
command.
.It Cm disble | enable
Temporarily disable, or enable, daemon.
.It Cm loglevel Ar LEVEL
Adjust daemon log level: none, err, warn,
.Ar notice ,
info, debug.
.\" Change daemon log level, see also
.\" .Cm debug .
.It Cm reload
Reload daemon configuration file, like sending SIGHUP, but the command
does not return until
.Nm watchdogd
has completed.
.It Cm reboot Op MSEC
Alias to
.Cm reset .
.It Cm reset Op MSEC
Perform system reset, with an optional millisecond delay.  On systems with
.Xr finit 8 ,
.Nm watchdogd
will ask Finit to do an orderly shutdown (stop services, sync and
unmount all file systems) before performing the WDT reset.
.It Cm status
Query status of daemon and show last reset cause, default command.
.It Cm test Op TEST
Run built-in tests of process supervisor functionality in daemon.  These
tests can be disabled at build time, so they may not be available in the
installed
.Nm .
The default test, if none is selected, runs the complete cycle.  You may
want to run these tests with the
.Fl -verbose
option to enable output.
.Pp
.Bl -tag -width false-unsubscribe -compact -offset indent
.It Cm complete-cycle
Verify subscribe, kick, and unsubscribe (no reboot)
.It Cm disable-enable
Verify WDT disable, and re-enable (no reboot)
.It Cm false-ack
Verify kick with invalid ACK (reboot)
.It Cm false-unsubscribe
Verify unsubscribe with invalid ACK (reboot)
.It Cm failed-kick
Verify reboot on missing kick (reboot)
.It Cm no-kick
Verify reboot on missing first kick (reboot)
.It Cm premature-trigger
Verify no premature trigger before unsubscribe (reboot)
.El
.It Cm version
Show program version.
.El
.Sh FILES
.Bl -tag -width /run/watchdogd.status -compact
.It Pa /etc/watchdogd.conf
Daemon configuration file. Read once when starting up and on SIGHUP or
.Cm reload
command.
.It Pa /run/watchdogd.status
Read to present WDT status and reset cause
.It Pa /run/watchdogd.sock
Used to connect to
.Nm watchdogd
.El
.Sh SEE ALSO
.Xr watchdogd 8
.Xr watchdogd.conf 5
.Sh AUTHORS
.Nm watchdogd
is an improved version of the original, created by Michele d'Amico and
adapted to uClinux-dist by Mike Frysinger.  It is maintained by Joachim
Nilsson at
.Lk https://github.com/troglobit/watchdogd "GitHub" .
