#!/bin/sh
#/etc/init.d/watchdog: start system watchdog daemon.

### BEGIN INIT INFO
# Provides:          watchdogd
# Short-Description: Start system watchdog daemon
# Required-Start:    $all
# Required-Stop:     $all
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin

test -x /usr/sbin/watchdogd || exit 0

# Set run_watchdog to 1 to start watchdog or 0 to disable it.
run_watchdog=0

# Specify additional watchdog options here (see manpage).
watchdog_options=""

# Specify module to load
watchdog_module="none"

NAME=watchdogd
DAEMON=/usr/sbin/watchdogd

STOP_RETRY_SCHEDULE='TERM/10/forever/KILL/1'

# Get lsb functions
. /lib/lsb/init-functions

case "$1" in
  start)
    if [ $run_watchdog = 1 ]
    then
    	# do we have to load a module?
	[ "${watchdog_module:-none}" != "none" ] && /sbin/modprobe $watchdog_module

	log_begin_msg "Starting watchdog daemon..."
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
             --exec $DAEMON -- $watchdog_options
	log_end_msg $?
    fi
    ;;

  stop)
    if [ $run_watchdog = 1 ]
    then
	log_begin_msg "Stopping watchdog daemon..."
	start-stop-daemon --stop --quiet --retry $STOP_RETRY_SCHEDULE \
	    --pidfile /var/run/$NAME.pid
	log_end_msg $?
    fi
    ;;

  restart)
    $0 force-reload
    ;;

  force-reload)
    if [ $run_watchdog = 0 ]; then exit 0; fi
    log_daemon_msg "Restarting $NAME"
    log_progress_msg "Stopping watchdog daemon..."
    start-stop-daemon --stop --pidfile /var/run/$NAME.pid --quiet \
	--retry $STOP_RETRY_SCHEDULE || log_end_msg $?
    log_progress_msg "Starting watchdog daemon..."
    start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
	--exec $DAEMON -- $watchdog_options
    log_end_msg $?
    ;;

  status)
    status_of_proc "$DAEMON" watchdog
    ;;

  *)
    echo "Usage: /etc/init.d/watchdog {start|stop|restart|force-reload|status}"
    exit 1

esac

exit 0
